### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by ehemsley**
- fixed inconsistent trailing whitespace 
- remove redeclaration of 'any' as 'unknown' 
- updated some function definitions to be more consistent with LOVE usage

### CODE REVIEW

**Comment by ehemsley** [comment]
Just for clarification, I should mention that I'm using these definition files to develop for LOVE 11.2

**Comment by ehemsley** [comment]
Hmm my test project is failing to build after I merged our changes together so let me figure out what's going on before merging.

**Comment by ehemsley** [comment]
My test project builds correctly now, feel free to merge.

**Comment by hazzard993** [comment]
Thanks so much, a lot of really great improvements!

**Pull request merged**
